version: "3.3"

services:
  iamdman-sssai:
    build:
      context: .
      args:
        TZ: America/New_York
    image: iamdman/sssai:latest
    container_name: iamdman-sssai
    volumes:
      - ./captureDir:/captureDir
      - ./config:/config
    environment:
      LOG_LEVEL: DEBUG
    ports:
      - "4242:80"
