version: "3.3"

services:
  iamdman-sssai:
    build:
      context: .
      args:
        TZ: America/New_York
    image: iamdman/sssai:latest
    container_name: iamdman-ssaai
    volumes:
      # mkdir -p ./data/captures
      - /volume1/docker/sssAI/captureDir:/captureDir
      - /volume1/docker/sssAI/config:/config
    ports:
      - "4242:80"
